### ISSUE TITLE
Cannot change version

### ISSUE THREAD

**Issue by PatrickWhitehouse** [ddev/ddev-opensearch#3]
I'm trying to use 2.12.0 and I have set this inside `.ddev/opensearch/Dockerfile `but when checking the version by visiting the url echoed in `ddev describe`, I'm consistently seeing 2.13.0.

**Comment by rfay** [comment]
Please try removing your existing opensearch image:
```
docker rmi -f ddev-<projectname>-opensearch
```

or

```
~/.ddev/bin/docker-compose -f .ddev/.ddev-docker-compose-full.yaml build --no-cache --progress=plain
```

**Comment by cmuench** [comment]
Related to #4

**Comment by cmuench** [comment]
@PatrickWhitehouse Did the tip of @rfay help you?

**Comment by PatrickWhitehouse** [comment]
> @PatrickWhitehouse Did the tip of @rfay help you?

@cmuench - Nope. I have just tried the suggested fix above, and i'm still seeing 2.13.0 despite having 2.12.0 set.

**Comment by cmuench** [comment]
> > @PatrickWhitehouse Did the tip of @rfay help you?
> 
> @cmuench - Nope. I have just tried the suggested fix above, and i'm still seeing 2.13.0 despite having 2.12.0 set.

ok. I will try it on my machine.

**Comment by cmuench** [comment]
@PatrickWhitehouse I was able to run 2.12.0 on my machine.
I just pushed my example project to Github as reference.
https://github.com/cmuench/ddev-opensearch-2.12.0-example

**Comment by stasadev** [comment]
@PatrickWhitehouse,

You need to delete the existing opensearch volume before the downgrade:

```
ddev stop

docker volume ls | grep opensearch # to see the volume name

docker volume rm ddev-<projectname>_opensearch
```

**Comment by PatrickWhitehouse** [comment]
@stasadev - After the above, is it just a case of restarting via `ddev restart`? And to confirm, I can see the version by following the url given in `ddev describe` ?

**Comment by stasadev** [comment]
As you can see, I added `ddev stop` before deleting the volume, so it doesn't really matter what you will run afterwards, `ddev start` or `ddev restart`, and yes, if you changed the version in the `.ddev/opensearch/Dockerfile` and `docker-compose.opensearch.yaml`, and removed `#ddev-generated`, it should work.

> After the above, is it just a case of restarting via `ddev restart`?

As you can see, I added `ddev stop` before deleting the volume, so it doesn't matter if you run `ddev start` or `ddev restart` afterwards, each will do its job.

> And to confirm, I can see the version by following the url given in `ddev describe` ?

Yes, when you change the version in `.ddev/opensearch/Dockerfile` and `docker-compose.opensearch.yaml` and remove `#ddev-generated` from these files, and have the old opensearch volume removed, it should work.

**Comment by PatrickWhitehouse** [comment]
Really strange because I'm able to swap the version of the dashboard fine. 2.12.0 seems to show 2.13.0 if I curl the url for the ouput.

**Comment by stasadev** [comment]
Try this with a new test project:

```
mkdir test-opensearch && cd test-opensearch
ddev config --auto
ddev get ddev/ddev-opensearch
```

Modify  `.ddev/opensearch/Dockerfile` and `.ddev/docker-compose.opensearch.yaml` and run `ddev start`.

**Comment by cmuench** [comment]
@PatrickWhitehouse Did the recommendation of @stasadev work for you?

**Comment by cmuench** [comment]
I close this issue due to inactivity.

**Comment by rdeelstra** [comment]
Faced the same issue, while other versions did work ok, the 2.12.0 was somehow linked to the latest version through the docker cache it seems.
Eventually I had to do this to make it work @PatrickWhitehouse:
`docker system prune -a`
