### ISSUE TITLE
All installed files (like Dockerfile) must have #ddev-generated

### ISSUE THREAD

**Issue by rfay** [ddev/ddev-opensearch#4]
All installed files must have `#ddev-generated` in them, to allow `ddev get` or `ddev get --remove` to mess with them.

Currently at least the Dockerfile does not. Please add `#ddev-generated` to that and also make sure that `ddev get --remove` works cleanly. 

Thanks!

**Comment by cmuench** [comment]
The comment was added to the Dockerfile. I did not see any other file where the comment is missing.
I just released the change as 2.0.1.

**Comment by rfay** [comment]
Thanks!
